In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV,StratifiedKFold
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np

In [15]:
data=pd.read_csv('pollution.csv')
data

Temperature  Humidity  PM2.5   PM10   NO2   SO2    CO  \
0            29.8      59.1    5.2   17.9  18.9   9.2  1.72   
1            28.3      75.6    2.3   12.2  30.8   9.7  1.64   
2            23.1      74.7   26.7   33.8  24.4  12.6  1.63   
3            27.1      39.1    6.1    6.3  13.5   5.3  1.15   
4            26.5      70.7    6.9   16.0  21.9   5.6  1.01   
...           ...       ...    ...    ...   ...   ...   ...   
4995         40.6      74.1  116.0  126.7  45.5  25.7  2.11   
4996         28.1      96.9    6.9   25.0  25.3  10.8  1.54   
4997         25.9      78.2   14.2   22.1  34.8   7.8  1.63   
4998         25.3      44.4   21.4   29.0  23.7   5.7  0.89   
4999         24.1      77.9   81.7   94.3  23.2  10.5  1.38   

      Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                               6.3                 319    Moderate  
1                               6.0                 611    Moderate  
2                               5.2                 619    Moderate  
3                              11.1                 551        Good  
4                              12.7                 303        Good  
...                             ...                 ...         ...  
4995                            2.8                 765   Hazardous  
4996                            5.7                 709    Moderate  
4997                            9.6                 379    Moderate  
4998                           11.6                 241        Good  
4999                            8.3                 461    Moderate  

[5000 rows x 10 columns]

In [16]:
data.isna().sum()

Temperature                      0
Humidity                         0
PM2.5                            0
PM10                             0
NO2                              0
SO2                              0
CO                               0
Proximity_to_Industrial_Areas    0
Population_Density               0
Air Quality                      0
dtype: int64

In [17]:
X=data.drop(['Air Quality'],axis=1)
y=data[['Air Quality']]
X

Temperature  Humidity  PM2.5   PM10   NO2   SO2    CO  \
0            29.8      59.1    5.2   17.9  18.9   9.2  1.72   
1            28.3      75.6    2.3   12.2  30.8   9.7  1.64   
2            23.1      74.7   26.7   33.8  24.4  12.6  1.63   
3            27.1      39.1    6.1    6.3  13.5   5.3  1.15   
4            26.5      70.7    6.9   16.0  21.9   5.6  1.01   
...           ...       ...    ...    ...   ...   ...   ...   
4995         40.6      74.1  116.0  126.7  45.5  25.7  2.11   
4996         28.1      96.9    6.9   25.0  25.3  10.8  1.54   
4997         25.9      78.2   14.2   22.1  34.8   7.8  1.63   
4998         25.3      44.4   21.4   29.0  23.7   5.7  0.89   
4999         24.1      77.9   81.7   94.3  23.2  10.5  1.38   

      Proximity_to_Industrial_Areas  Population_Density  
0                               6.3                 319  
1                               6.0                 611  
2                               5.2                 619  
3                              11.1                 551  
4                              12.7                 303  
...                             ...                 ...  
4995                            2.8                 765  
4996                            5.7                 709  
4997                            9.6                 379  
4998                           11.6                 241  
4999                            8.3                 461  

[5000 rows x 9 columns]

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)
X_train

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
4884         24.3      62.5    1.1   9.6  20.8   7.0  1.08   
3163         26.7      65.2    2.7   7.0  17.6   6.8  1.02   
490          23.6      51.9   11.0  13.6  27.9   4.3  1.20   
862          29.6      56.4   17.2  35.2  20.7   4.5  1.70   
1740         21.4      57.5   12.9  18.0  20.6   5.7  1.23   
...           ...       ...    ...   ...   ...   ...   ...   
4426         30.0      59.7   59.3  68.8  22.1   7.4  1.39   
466          27.7      54.0   17.6  23.2  24.6  11.1  1.27   
3092         24.2      67.6   19.4  35.1  24.2   9.6  1.91   
3772         21.4      76.4   15.3  22.1  12.4   3.4  0.96   
860          34.4     103.1   29.2  42.2  54.4  23.6  3.37   

      Proximity_to_Industrial_Areas  Population_Density  
4884                           10.9                 567  
3163                           11.1                 510  
490                            12.1                 474  
862                             6.3                 649  
1740                           18.1                 233  
...                             ...                 ...  
4426                            5.1                 412  
466                             7.8                 638  
3092                            6.2                 422  
3772                           16.3                 420  
860                             3.7                 614  

[3750 rows x 9 columns]

In [19]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [20]:
data['Air Quality'].unique()

array(['Moderate', 'Good', 'Hazardous', 'Poor'], dtype=object)

In [21]:
model=LogisticRegression(multi_class='ovr')
penalty = ['l1', 'l2', 'elasticnet']  # Regularization methods
C_values = [100, 10, 1.0, 0.1, 0.01]  # Regularization strength
solver = ['liblinear', 'saga']  # Only solvers compatible with l1 and elasticnet
multiclass=['ovr','multinomial']
param_grid = {
    'penalty': penalty,
    'C': C_values,
    'solver': solver
}
param_grid

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['liblinear', 'saga']}

In [22]:
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=param_grid,scoring='accuracy',cv=cv)
grid.fit(X_train,y_train)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mahap\One

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['liblinear', 'saga']},
             scoring='accuracy')

In [23]:
grid.best_params_

{'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}

In [24]:
y_pred=grid.predict(X_test)
y_pred

array(['Hazardous', 'Good', 'Moderate', ..., 'Moderate', 'Good', 'Good'],
      dtype=object)

In [25]:
print("The accuracy score for logistic regression with hyperparameter tuning is ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy score for logistic regression with hyperparameter tuning is  0.8904
[[508   0   0   0]
 [  0 106   4  22]
 [  2   0 359  20]
 [  0  16  73 140]]
              precision    recall  f1-score   support

        Good       1.00      1.00      1.00       508
   Hazardous       0.87      0.80      0.83       132
    Moderate       0.82      0.94      0.88       381
        Poor       0.77      0.61      0.68       229

    accuracy                           0.89      1250
   macro avg       0.86      0.84      0.85      1250
weighted avg       0.89      0.89      0.89      1250



In [27]:
kmeans=KNeighborsClassifier()
param_grid = {
    'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10],  # Test a range of clusters
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],            # Algorithms for optimization
}
param_grid

{'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10],
 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

In [28]:
gridcv=GridSearchCV(estimator=kmeans,param_grid=param_grid,scoring='accuracy',cv=cv)
gridcv.fit(X_train,y_train)

c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\.vscode\ML-DL-NLP\myenv\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\mahap\OneDrive\Desktop\C++,JS python codes\

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [29]:
gridcv.best_params_

{'algorithm': 'auto', 'n_neighbors': 10}

In [30]:
y_pred=gridcv.predict(X_test)
y_pred

array(['Hazardous', 'Good', 'Good', ..., 'Moderate', 'Good', 'Good'],
      dtype=object)

In [31]:
print("The accuracy score for K means classifier  with hyperparamter tuning is ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

The accuracy score for K means classifier  with hyperparamter tuning is  0.9264
[[508   0   0   0]
 [  0  95   0  37]
 [  9   0 362  10]
 [  0  11  25 193]]
              precision    recall  f1-score   support

        Good       0.98      1.00      0.99       508
   Hazardous       0.90      0.72      0.80       132
    Moderate       0.94      0.95      0.94       381
        Poor       0.80      0.84      0.82       229

    accuracy                           0.93      1250
   macro avg       0.90      0.88      0.89      1250
weighted avg       0.93      0.93      0.93      1250

